project_id = "rforophgmeiueauuxhga"

[functions.analyze-screenshot]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = true

[functions.firecrawl-search]
verify_jwt = true

[functions.firecrawl-map]
verify_jwt = true

[functions.auto-retry-imports]
verify_jwt = false

[functions.ingest-browser-sync]
verify_jwt = false

[functions.hyperbeam-session]
verify_jwt = false
