project_id = "rforophgmeiueauuxhga"

[functions.analyze-screenshot]
verify_jwt = true

[functions.firecrawl-scrape]
verify_jwt = true

[functions.firecrawl-search]
verify_jwt = true

[functions.firecrawl-map]
verify_jwt = true
