
ALTER TABLE public.pending_applications
  ADD COLUMN IF NOT EXISTS alias TEXT,
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS occupation TEXT,
  ADD COLUMN IF NOT EXISTS hobbies TEXT,
  ADD COLUMN IF NOT EXISTS character_traits TEXT[],
  ADD COLUMN IF NOT EXISTS turn_ons TEXT,
  ADD COLUMN IF NOT EXISTS boundaries TEXT,
  ADD COLUMN IF NOT EXISTS content_types TEXT[],
  ADD COLUMN IF NOT EXISTS niche TEXT[],
  ADD COLUMN IF NOT EXISTS attracted_to TEXT,
  ADD COLUMN IF NOT EXISTS favorite_music TEXT,
  ADD COLUMN IF NOT EXISTS favorite_food TEXT,
  ADD COLUMN IF NOT EXISTS persona_data JSONB;
